name: JAR Package

on:
  push:
    tags: 'v*'
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Create JAR file
      run: ./gradlew shadowJar
      
    - name: Install Python dependencies
      run: |
        python3 -m pip install gitpython termcolor requests
    - name: Upload Assets
      run: |
        python3 .github/workflows/make_release.py target/release/cork $GITHUB_TOKEN
